version: '3'
services:
    api:
        container_name: api-cont
        build: .
        environment:
            DEV_MODE: 1
            DB_USER: root
            DB_PASSWORD: my_secret_password
            DB_HOST: db
            DB_NAME: server_db
        links:
            - db
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes:
            - .:/api
    db:
        image: mysql:5.7
        container_name: flask_mysql
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
            MYSQL_DATABASE: server_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:

