"""Updated events table

Revision ID: 1bc2e71d5c24
Revises: db98fcf7a90f
Create Date: 2021-10-12 21:02:34.105087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bc2e71d5c24'
down_revision = 'db98fcf7a90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('events', sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('events', 'attendees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('attendees', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('events', 'time_created')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
