"""Renamed column in events

Revision ID: 50d1409e8087
Revises: 6a0794bb0269
Create Date: 2021-10-14 16:24:48.014948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50d1409e8087'
down_revision = '6a0794bb0269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('events', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('events', 'event_id')
    # ### end Alembic commands ###
