"""Added count of places on an event

Revision ID: 6a0794bb0269
Revises: 1bc2e71d5c24
Create Date: 2021-10-13 20:07:17.289093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0794bb0269'
down_revision = '1bc2e71d5c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('places', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'places')
    # ### end Alembic commands ###
